apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: application-registry
    version: v0.1
  name: application-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      application: application-registry
  template:
    metadata:
      labels:
        application: application-registry
        version: v0.1
    spec:
      containers:
      - name: application-registry
        image: hjacobs/application-registry-example
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 1m
            memory: 20Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
