apiVersion: v1
kind: Service
metadata:
  labels:
    application: application-registry
  name: application-registry
spec:
  selector:
    application: application-registry
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
